// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0oQCF7os8m6-7ASFohuKfLBnRCB-jnkw',
    appId: '1:816811330862:web:faad75513c025682befebf',
    messagingSenderId: '816811330862',
    projectId: 'findme-4f303',
    authDomain: 'findme-4f303.firebaseapp.com',
    storageBucket: 'findme-4f303.appspot.com',
    measurementId: 'G-TV5JWSCZ5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjZQTk_8jjjHkQzEKRt-p10WqpDAsPTKM',
    appId: '1:816811330862:android:6f6e5f99f6c61259befebf',
    messagingSenderId: '816811330862',
    projectId: 'findme-4f303',
    storageBucket: 'findme-4f303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-qbei6Wy9qfZ0u6y860dSEys2IR7ymM',
    appId: '1:816811330862:ios:cc39aa54030ddeb2befebf',
    messagingSenderId: '816811330862',
    projectId: 'findme-4f303',
    storageBucket: 'findme-4f303.appspot.com',
    iosBundleId: 'com.example.findIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-qbei6Wy9qfZ0u6y860dSEys2IR7ymM',
    appId: '1:816811330862:ios:cc39aa54030ddeb2befebf',
    messagingSenderId: '816811330862',
    projectId: 'findme-4f303',
    storageBucket: 'findme-4f303.appspot.com',
    iosBundleId: 'com.example.findIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0oQCF7os8m6-7ASFohuKfLBnRCB-jnkw',
    appId: '1:816811330862:web:dfe123cbdbc9d8cfbefebf',
    messagingSenderId: '816811330862',
    projectId: 'findme-4f303',
    authDomain: 'findme-4f303.firebaseapp.com',
    storageBucket: 'findme-4f303.appspot.com',
    measurementId: 'G-9RQLQ20V73',
  );
}
